### ISSUE TITLE
Solution without Python

### ISSUE THREAD

**Issue by felixfbecker** [ceddlyburge/codecov-on-appveyor#3]
Just wanted to share this solution I came up with that doesn't require Python or pip and uses the bash script:

```yml
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "./coverage.xml"
```

Ideally, it would be awesome to have a PowerShell version of the script, but the AppVeyor environment always includes git, which always includes bash, so this always works without having to install anything.

**Comment by ceddlyburge** [comment]
Hi Felix, that looks great.

I'll open up a pull request on the AppVeyor website to update the blog post.

Thanks!

Cedd
