### ISSUE TITLE
Coverage collection broken

### ISSUE THREAD

**Issue by Flamefire** [ceddlyburge/codecov-on-appveyor#5]
I wanted to try this and check how the coverage file looks like but it doesn't collect any coverage data at all:

> No results, this could be for a number of reasons. The most common reasons are:
1) missing PDBs for the assemblies that match the filter please review the
output file and refer to the Usage guide (Usage.rtf) about filters.
2) the profiler may not be registered correctly, please refer to the Usage
guide and the -register switch

See e.g. https://ci.appveyor.com/project/ceddlyburge/codecov-on-appveyor/builds/31175529

**Comment by Flamefire** [comment]
Likely cause and solution: https://github.com/OpenCover/opencover/issues/849

--> Use `-register:administrator`

**Comment by ceddlyburge** [comment]
Hi there, I also see this problem. I'll investigate.

**Comment by Flamefire** [comment]
I can confirm that my suggestion fixes this.

**Comment by Flamefire** [comment]
I updated my PR: #4

Feel free to merge this or take commits from there

**Comment by ceddlyburge** [comment]
Fixed by #4
